// Code generated by Slice Machine. DO NOT EDIT.

import Image from './Image';
import Models from './Models';
import Text from './Text';

export {
	Image,
	Models,
	Text,
};

export const components = {
	image: Image,
	models: Models,
	text: Text,
};
